FROM node:lts-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

#This can be ommitted then using volumes, 
#but better to leave it, in case in the future we want to not include valumes in the compose file
COPY . .

CMD ["npm", "run", "start"]
