name: Deploy Frontend
on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u kirtimanb23 -p Dangerous1!
      - run: docker build -t kirtimanb23/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true kirtimanb23/react-test npm test
